(lang dune 3.12)

(name day06)

(generate_opam_files true)

(source
 (github Treeniks/advent-of-code))

(authors "Thomas Lindae")

(package
 (name day06)
 (depends ocaml dune))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/dune-files.html#dune-project
