alias r := run
alias b := build

alias rt := run-test
alias bt := build-test

alias c := clean

run input="input.txt": build
    ./day01 {{ input }}

build: assemble-main assemble-utils link

assemble-main:
    nasm -f elf64 -o day01.o day01.asm

assemble-utils:
    nasm -f elf64 -o day01_utils.o day01_utils.asm

link:
    ld --output day01 -x -pie -z relro -z now -z noexecstack day01.o day01_utils.o -lc --dynamic-linker /lib/ld-linux-x86-64.so.2

run-test: build-test
    ./test

build-test: assemble-utils
    gcc -c -o test.o test.c
    gcc -o test test.o day01_utils.o

clean:
    rm -f day01.o
    rm -f day01_utils.o
    rm -f day01
    rm -f test.o
    rm -f test
