run: build
    ./day01

build: assemble-main assemble-utils link

assemble-main:
    nasm -f elf64 -o day01.o day01.asm

assemble-utils:
    nasm -f elf64 -o day01_utils.o day01_utils.asm

link:
    ld --output day01 -x --pie day01.o day01_utils.o -lc --dynamic-linker /lib/ld-linux-x86-64.so.2

run-test: build-test
    ./test

build-test: assemble-utils
    gcc -c -o test.o test.c
    gcc -o test test.o day01_utils.o

clean:
    rm -f day01.o
    rm -f day01_utils.o
    rm -f day01
    rm -f test.o
    rm -f test
