build_command := if os_family() == "windows" {
    "cd build && cmake .. -G 'MinGW Makefiles' && mingw32-make"
} else {
    "cd build && cmake .. && make"
}

run: build
    build/day10

test: build
    build/day10_test

build:
    mkdir -p build
    {{build_command}}
    cp build/compile_commands.json .

clean:
    rm -rf build
    rm -f compile_commands.json
